name: farming-effect
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc repro

          git fetch --prune
          echo "## Current metrices" > report.md
          dvc metrics show --md >> report.md
          
          echo "## Difference in the metrices" >> report.md
          dvc metrics diff --md master >> report.md

          # Add figures to the report
          echo "## Validating the result by region" >> report.md
          echo "![by_region](./by_region.png)" >> report.md
          
          cml comment create report.md
       
